# Generated by Django 2.0.4 on 2018-04-10 23:11

import apps.celebritys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='셀럽명')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.celebritys.models.celebrity_image, verbose_name='연예인 사진')),
                ('celeb_type', models.CharField(choices=[('g', '그룹/팀'), ('s', '개인')], default='s', max_length=2, verbose_name='유형')),
                ('debut', models.DateField(blank=True, null=True, verbose_name='데뷔일')),
                ('real_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='본명')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('sex', models.CharField(blank=True, choices=[('m', '남자'), ('f', '여자')], max_length=2, null=True, verbose_name='성별')),
            ],
            options={
                'verbose_name': '연예인',
                'verbose_name_plural': '연예인들',
                'db_table': 'celebrity',
            },
        ),
    ]
