# Generated by Django 2.0.3 on 2018-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='연예인명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='연예인 사진')),
                ('celeb_type', models.CharField(choices=[('g', '그룹/팀'), ('s', '개인')], default='s', max_length=2, verbose_name='연예인 유형')),
            ],
            options={
                'verbose_name': '연예인',
                'verbose_name_plural': '연예인들',
                'db_table': 'celebrity',
            },
        ),
    ]
