# Generated by Django 2.0.3 on 2018-03-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='debut',
            field=models.DateField(blank=True, null=True, verbose_name='데뷔일'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='real_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='본명'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', '남자'), ('f', '여자')], max_length=2, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='celeb_type',
            field=models.CharField(choices=[('g', '그룹/팀'), ('s', '개인')], default='s', max_length=2, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='name',
            field=models.CharField(max_length=50, verbose_name='셀럽명'),
        ),
    ]
