# Generated by Django 2.0.4 on 2018-04-03 05:54

import apps.celebritys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritys', '0002_auto_20180329_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.celebritys.models.celebrity_profile_image, verbose_name='연예인 사진'),
        ),
    ]
