# Generated by Django 2.0.4 on 2018-04-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_staff',
            new_name='is_manager',
        ),
    ]
