# Generated by Django 2.0.7 on 2018-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20180411_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='콘텐츠 URL'),
        ),
    ]
