# Generated by Django 2.0.4 on 2018-04-03 05:54

import apps.entertainments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='기획사명')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.entertainments.models.entertainment_image, verbose_name='사진')),
                ('start', models.DateField(blank=True, null=True, verbose_name='설립일')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='홈페이지')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='가입코드')),
            ],
            options={
                'verbose_name': '기획사',
                'verbose_name_plural': '기획사들',
                'db_table': 'entertainment',
            },
        ),
    ]
