# Generated by Django 2.0.4 on 2018-04-10 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebritys', '0002_auto_20180410_1351'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('s', 'Super'), ('n', 'Normal')], default='n', max_length=10, verbose_name='직책')),
                ('celebrity', models.ManyToManyField(blank=True, to='celebritys.Celebrity', verbose_name='연예인')),
                ('entertainment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='기획사')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_user', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '기획사 매니저',
                'verbose_name_plural': '기획서 매니저들',
                'db_table': 'entertainment_manager',
            },
        ),
    ]
