# Generated by Django 2.0.4 on 2018-04-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0003_auto_20180410_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='position',
            new_name='manager_type',
        ),
    ]
