# Generated by Django 2.0.4 on 2018-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0004_auto_20180410_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_type',
            field=models.CharField(choices=[('s', 'Super'), ('n', 'Normal')], default='n', max_length=10, verbose_name='권한'),
        ),
    ]
