# Generated by Django 2.0.4 on 2018-04-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0005_auto_20180410_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='entertainment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='entertainments.Entertainment', verbose_name='기획사'),
        ),
    ]
