# Generated by Django 2.0.4 on 2018-05-15 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='', max_length=1, verbose_name='알림 유형'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
    ]
